
password.length.min=5
password.length.max=12

validation.errMsg.lowerCaseAlphabetDitgitOnlyAtLeastOneOfEachValidator=Should be lower case alphabet and digit only with at least one of each
validation.errMsg.noRepeatSequenceVaildator=Not repeat sequence just after the sequence
validation.errMsg.passwordLengthValidator=Password length should be between {0} to {1}